In [3]:
import numpy as np
import matplotlib.pylab as plt

In [4]:
a = 121.3456789
print(f"{a:.6}")
b = 123456789
print(f"{b:,f}")

121.346
123,456,789.000000


In [5]:
a = np.array([0.3,9,4.3])
print(a)

[0.3 9.  4.3]


In [6]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [7]:
a = np.linspace(0, 100, 11)
print(a)

[  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


<img src="https://zhaoty2077.github.io/images/photo_life_Yunnan_cutted_reduced.jpg">

<img src="https://zhaoty2077.github.io/images/photo_life_Yunnan_cutted_reduced.jpg">

![photo](https://zhaoty2077.github.io/images/photo_life_Yunnan_cutted_reduced.jpg)

### linspace和logspace的用法以及与arange函数的区别

linspace和logspace等生成一系列数字的np函数用法都是function(y轴下限,y轴上限,数字数量)，不同的在于函数的不同，如logspace相当于是y=log10(x)的函数. 和arange不同的就是**第三个参数**，arange指定的是间隔大小，xxxspace函数指定的生成数量。如果不指定生成数量一般这些函数默认的都是50个。

In [37]:
a = np.logspace(1,3,10)
a

array([  10.        ,   16.68100537,   27.82559402,   46.41588834,
         77.42636827,  129.1549665 ,  215.443469  ,  359.38136638,
        599.48425032, 1000.        ])

In [45]:
y = np.linspace(1,50)
y
z = np.logspace(1,50)
z

array([1.e+01, 1.e+02, 1.e+03, 1.e+04, 1.e+05, 1.e+06, 1.e+07, 1.e+08,
       1.e+09, 1.e+10, 1.e+11, 1.e+12, 1.e+13, 1.e+14, 1.e+15, 1.e+16,
       1.e+17, 1.e+18, 1.e+19, 1.e+20, 1.e+21, 1.e+22, 1.e+23, 1.e+24,
       1.e+25, 1.e+26, 1.e+27, 1.e+28, 1.e+29, 1.e+30, 1.e+31, 1.e+32,
       1.e+33, 1.e+34, 1.e+35, 1.e+36, 1.e+37, 1.e+38, 1.e+39, 1.e+40,
       1.e+41, 1.e+42, 1.e+43, 1.e+44, 1.e+45, 1.e+46, 1.e+47, 1.e+48,
       1.e+49, 1.e+50])

In [53]:
a  =np.ones(4)
b = np.empty(4)
print(a)
print(b)
a.shape

[1. 1. 1. 1.]
[1. 1. 1. 1.]


(4,)

In [64]:
a = np.array([[[1,2],[3,4],[5,6]],[[1,2],[3,4],[5,6]]])
a

array([[[1, 2],
        [3, 4],
        [5, 6]],

       [[1, 2],
        [3, 4],
        [5, 6]]])

转换shape的时候是三个维度相乘等于总共的数的数量

In [79]:
a1 = np.array([1,2,3,4,5,6,7,8])
a1.shape = 2,2,2
print(a1)
c = np.array([1])
c.shape = 1,1,1,1
c

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


array([[[[1]]]])

In [75]:
np.ones((2,2,2,2))

array([[[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]],


       [[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]]])

In [84]:
x = np.linspace(1,100,7)
print(x)
np.sin(x)

[  1.   17.5  34.   50.5  67.   83.5 100. ]


array([ 0.84147098, -0.97562601,  0.52908269,  0.23237376, -0.85551998,
        0.96945567, -0.50636564])